default: cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java
	javac cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java

run: cpsc2150/connectX/GameBoard.class cpsc2150/connectX/Connect4Game.class
	java cpsc2150/connectX.Connect4Game

clean:
	rm -f *.class

