default: cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/AbsGameBoard.java
	javac cpsc2150/connectX/GameBoard.java cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/AbsGameBoard.java

run: cpsc2150/connectX/GameBoard.class cpsc2150/connectX/Connect4Game.class cpsc2150/connectX/IGameBoard.class cpsc2150/connectX/GameBoardMem.class cpsc2150/connectX/AbsGameBoard.java
	java cpsc2150/connectX.Connect4Game

clean:
	rm -f *.class

