default: cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java
	javac -Xlint cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/Customer.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java

run: cpsc2150/mortgages/MortgageApp.class cpsc2150/mortgages/IMortgage.class cpsc2150/mortgages/ICustomer.class cpsc2150/mortgages/AbsMortgage.class cpsc2150/mortgages/AbsCustomer.class cpsc2150/mortgages/Mortgage.class cpsc2150/mortgages/Customer.class cpsc2150/mortgages/IMortgageController.class cpsc2150/mortgages/IMortgageView.java
	java cpsc2150.mortgages.MortgageApp
