default: cpsc2150/setFun/ArraySet.java cpsc2150/setFun/ISet.java cpsc2150/setFun/MultiSetApp.java cpsc2150/setFun/ListSet.java
	javac cpsc2150/setFun/ArraySet.java cpsc2150/setFun/ISet.java cpsc2150/setFun/MultiSetApp.java cpsc2150/setFun/ListSet.java

run: cpsc2150/setFun/ArraySet.class cpsc2150/setFun/ISet.class cpsc2150/setFun/MultiSetApp.class cpsc2150/setFun/ListSet.class
	java cpsc2150/setFun.MultiSetApp

clean:
	rm -f *.class



