default: cpsc2150/matrixFun/Matrix.java cpsc2150/matrixFun/MatrixApp.java
	javac cpsc2150/matrixFun/Matrix.java cpsc2150/matrixFun/MatrixApp.java

run: cpsc2150/matrixFun/MatrixApp.class cpsc2150/matrixFun/Matrix.class
	java cpsc2150/matrixFun.MatrixApp

clean:
	rm -f *.class
